config/routes.rb
Rails.application.routes.draw do
  resources :university_pulls
  resources :estimations
  resources :disciplines
  resources :universities
  resources :specialities
  resources :speciality_pulls
  resources :syllabuses
  resources :roles
  get 'sessions/new'
  resources :users
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/signup',   to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
end

app/controllers/syllabuses_controller.rb
class SyllabusesController < ApplicationController
  before_action :set_syllabus, only: [:show, :edit, :update, :destroy]

  # GET /syllabuses
  # GET /syllabuses.json
  def index
    @syllabuses = Syllabus.all
  end

  # GET /syllabuses/1
  # GET /syllabuses/1.json
  def show
  end

  # GET /syllabuses/new
  def new
    @syllabus = Syllabus.new
  end

  # GET /syllabuses/1/edit
  def edit
  end

  # POST /syllabuses
  # POST /syllabuses.json
  def create
    @syllabus = Syllabus.new(syllabus_params)

    respond_to do |format|
      if @syllabus.save
        format.html { redirect_to @syllabus, notice: 'Syllabus was successfully created.' }
        format.json { render :show, status: :created, location: @syllabus }
      else
        format.html { render :new }
        format.json { render json: @syllabus.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /syllabuses/1
  # PATCH/PUT /syllabuses/1.json
  def update
    respond_to do |format|
      if @syllabus.update(syllabus_params)
        format.html { redirect_to @syllabus, notice: 'Syllabus was successfully updated.' }
        format.json { render :show, status: :ok, location: @syllabus }
      else
        format.html { render :edit }
        format.json { render json: @syllabus.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /syllabuses/1
  # DELETE /syllabuses/1.json
  def destroy
    @syllabus.destroy
    respond_to do |format|
      format.html { redirect_to syllabuses_url, notice: 'Syllabus was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_syllabus
      @syllabus = Syllabus.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def syllabus_params
      params.require(:syllabus).permit(:school, :university, :coordinator, :document)
    end
end

app/helpers/syllabuses_helper.rb
module SyllabusesHelper
end

app/views/syllabuses/_form.html.erb
<%= form_with(model: syllabus, local: true) do |form| %>
  <% if syllabus.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(syllabus.errors.count, "error") %> prohibited this syllabus from being saved:</h2>

      <ul>
      <% syllabus.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :school %>
    <%= form.text_field :school %>
  </div>

  <div class="field">
    <%= form.label :university %>
    <%= form.text_field :university %>
  </div>

  <div class="field">
    <%= form.label :coordinator %>
    <%= form.text_field :coordinator %>
  </div>


  <%= form.file_field :document %>
  

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/syllabuses/edit.html.erb
<h1>Editing Syllabus</h1>

<%= render 'form', syllabus: @syllabus %>

<%= link_to 'Show', @syllabus %> |
<%= link_to 'Back', syllabuses_path %>

app/views/syllabuses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Syllabuses</h1>

<table>
  <thead>
    <tr>
      <th>School</th>
      <th>University</th>
      <th>Coordinator</th>
      <th>Document</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @syllabuses.each do |syllabus| %>
      <tr>
        <td><%= syllabus.school %></td>
        <td><%= syllabus.university %></td>
        <td><%= syllabus.coordinator %></td>
        <td><%= link_to "Document", syllabus.document.url(:original, false) %></td>
        <td><%= link_to 'Show', syllabus %></td>
        <td><%= link_to 'Edit', edit_syllabus_path(syllabus) %></td>
        <td><%= link_to 'Destroy', syllabus, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Syllabus', new_syllabus_path %>

app/views/syllabuses/new.html.erb
<h1>New Syllabus</h1>

<%= render 'form', syllabus: @syllabus %>


<%= link_to 'Back', syllabuses_path %>

app/views/syllabuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>School:</strong>
  <%= @syllabus.school %>
</p>

<p>
  <strong>University:</strong>
  <%= @syllabus.university %>
</p>

<p>
  <strong>Coordinator:</strong>
  <%= @syllabus.coordinator %>
</p>

<p>
  <strong>document:</strong>
  <%= @syllabus.document %>
</p>
<%= link_to 'Edit', edit_syllabus_path(@syllabus) %> |
<%= link_to 'Back', syllabuses_path %>