config/routes.rb
Rails.application.routes.draw do
  resources :university_pulls
  resources :estimations
  resources :disciplines
  resources :universities
  resources :specialities
  resources :speciality_pulls
  resources :syllabuses
  resources :roles
  get 'sessions/new'
  resources :users
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/signup',   to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
end

app/models/speciality_pull.rb
class SpecialityPull < ApplicationRecord
	has_many :specialities
	validates :key, presence: true
	validates :name, presence: true

	has_attached_file :ocen_list
	validates_attachment :ocen_list, :content_type => { :content_type => %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document)}

end

app/controllers/speciality_pulls_controller.rb
class SpecialityPullsController < ApplicationController
  before_action :set_speciality_pull, only: [:show, :edit, :update, :destroy]

  # GET /speciality_pulls
  # GET /speciality_pulls.json
  def index
    @speciality_pulls = SpecialityPull.all
  end

  # GET /speciality_pulls/1
  # GET /speciality_pulls/1.json
  def show
  end

  # GET /speciality_pulls/new
  def new
    @speciality_pull = SpecialityPull.new
  end

  # GET /speciality_pulls/1/edit
  def edit
  end

  # POST /speciality_pulls
  # POST /speciality_pulls.json
  def create
    @speciality_pull = SpecialityPull.new(speciality_pull_params)

    respond_to do |format|
      if @speciality_pull.save
        format.html { redirect_to @speciality_pull, notice: 'Speciality pull was successfully created.' }
        format.json { render :show, status: :created, location: @speciality_pull }
      else
        format.html { render :new }
        format.json { render json: @speciality_pull.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /speciality_pulls/1
  # PATCH/PUT /speciality_pulls/1.json
  def update
    respond_to do |format|
      if @speciality_pull.update(speciality_pull_params)
        format.html { redirect_to @speciality_pull, notice: 'Speciality pull was successfully updated.' }
        format.json { render :show, status: :ok, location: @speciality_pull }
      else
        format.html { render :edit }
        format.json { render json: @speciality_pull.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /speciality_pulls/1
  # DELETE /speciality_pulls/1.json
  def destroy
    @speciality_pull.destroy
    respond_to do |format|
      format.html { redirect_to speciality_pulls_url, notice: 'Speciality pull was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_speciality_pull
      @speciality_pull = SpecialityPull.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def speciality_pull_params
      params.require(:speciality_pull).permit(:key, :name, :ocen_list)
    end
end

app/helpers/speciality_pulls_helper.rb
module SpecialityPullsHelper
end

app/views/speciality_pulls/_form.html.erb
<%= form_with(model: speciality_pull, local: true) do |form| %>
  <% if speciality_pull.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(speciality_pull.errors.count, "error") %> prohibited this speciality_pull from being saved:</h2>

      <ul>
      <% speciality_pull.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :key %>
    <%= form.text_field :key %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <%= form.label "Оценочный лист" %>
  <%= form.file_field :ocen_list %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/speciality_pulls/edit.html.erb
<h1>Editing Speciality Pull</h1>

<%= render 'form', speciality_pull: @speciality_pull %>

<%= link_to 'Show', @speciality_pull %> |
<%= link_to 'Back', speciality_pulls_path %>

app/views/speciality_pulls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Speciality Pulls</h1>

<table>
  <thead>
    <tr>
      <th>Key</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @speciality_pulls.each do |speciality_pull| %>
      <tr>
        <td><%= speciality_pull.key %></td>
        <td><%= speciality_pull.name %></td>
        <td><%= link_to "Оценочный лист", speciality_pull.ocen_list.url(:original, false) %></td>
        <td><%= link_to 'Show', speciality_pull %></td>
        <td><%= link_to 'Edit', edit_speciality_pull_path(speciality_pull) %></td>
        <td><%= link_to 'Destroy', speciality_pull, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Speciality Pull', new_speciality_pull_path %>

app/views/speciality_pulls/new.html.erb
<h1>New Speciality Pull</h1>

<%= render 'form', speciality_pull: @speciality_pull %>

<%= link_to 'Back', speciality_pulls_path %>

app/views/speciality_pulls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Key:</strong>
  <%= @speciality_pull.key %>
</p>

<p>
  <strong>Name:</strong>
  <%= @speciality_pull.name %>
</p>

<p>
  <strong>Оценочный лист:</strong>
  <%= link_to "Оценочный лист", @speciality_pull.ocen_list.url(:original, false) %>
</p>
<%= link_to 'Edit', edit_speciality_pull_path(@speciality_pull) %> |
<%= link_to 'Back', speciality_pulls_path %>