config/routes.rb
Rails.application.routes.draw do
  resources :university_pulls
  resources :estimations
  resources :disciplines
  resources :universities
  resources :specialities
  resources :speciality_pulls
  resources :syllabuses
  resources :roles
  get 'sessions/new'
  resources :users
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/signup',   to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
end

app/models/university_pull.rb
class UniversityPull < ApplicationRecord
	has_many :universities
	has_many :users
	validates :key, presence: true
	validates :name, presence: true
end

app/controllers/university_pulls_controller.rb
class UniversityPullsController < ApplicationController
  before_action :set_university_pull, only: [:show, :edit, :update, :destroy]

  # GET /university_pulls
  # GET /university_pulls.json
  def index
    @university_pulls = UniversityPull.all
  end

  # GET /university_pulls/1
  # GET /university_pulls/1.json
  def show
  end

  # GET /university_pulls/new
  def new
    @university_pull = UniversityPull.new
  end

  # GET /university_pulls/1/edit
  def edit
  end

  # POST /university_pulls
  # POST /university_pulls.json
  def create
    @university_pull = UniversityPull.new(university_pull_params)

    respond_to do |format|
      if @university_pull.save
        format.html { redirect_to @university_pull, notice: 'University pull was successfully created.' }
        format.json { render :show, status: :created, location: @university_pull }
      else
        format.html { render :new }
        format.json { render json: @university_pull.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /university_pulls/1
  # PATCH/PUT /university_pulls/1.json
  def update
    respond_to do |format|
      if @university_pull.update(university_pull_params)
        format.html { redirect_to @university_pull, notice: 'University pull was successfully updated.' }
        format.json { render :show, status: :ok, location: @university_pull }
      else
        format.html { render :edit }
        format.json { render json: @university_pull.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /university_pulls/1
  # DELETE /university_pulls/1.json
  def destroy
    @university_pull.destroy
    respond_to do |format|
      format.html { redirect_to university_pulls_url, notice: 'University pull was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_university_pull
      @university_pull = UniversityPull.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def university_pull_params
      params.require(:university_pull).permit(:key, :name)
    end
end

app/helpers/university_pulls_helper.rb
module UniversityPullsHelper
end

app/views/university_pulls/_form.html.erb
<%= form_with(model: university_pull, local: true) do |form| %>
  <% if university_pull.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(university_pull.errors.count, "error") %> prohibited this university_pull from being saved:</h2>

      <ul>
      <% university_pull.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :key %>
    <%= form.number_field :key %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/university_pulls/edit.html.erb
<h1>Editing University Pull</h1>

<%= render 'form', university_pull: @university_pull %>

<%= link_to 'Show', @university_pull %> |
<%= link_to 'Back', university_pulls_path %>

app/views/university_pulls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>University Pulls</h1>

<table>
  <thead>
    <tr>
      <th>Key</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @university_pulls.each do |university_pull| %>
      <tr>
        <td><%= university_pull.key %></td>
        <td><%= university_pull.name %></td>
        <td><%= link_to 'Show', university_pull %></td>
        <td><%= link_to 'Edit', edit_university_pull_path(university_pull) %></td>
        <td><%= link_to 'Destroy', university_pull, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New University Pull', new_university_pull_path %>

app/views/university_pulls/new.html.erb
<h1>New University Pull</h1>

<%= render 'form', university_pull: @university_pull %>

<%= link_to 'Back', university_pulls_path %>

app/views/university_pulls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Key:</strong>
  <%= @university_pull.key %>
</p>

<p>
  <strong>Name:</strong>
  <%= @university_pull.name %>
</p>

<%= link_to 'Edit', edit_university_pull_path(@university_pull) %> |
<%= link_to 'Back', university_pulls_path %>